name: abhi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  path_provider: ^2.1.5
  cached_network_image: ^3.2.3
  get_it: ^8.0.2
  injectable: ^2.0.0
  connectivity_plus: ^4.0.0
  dartz: ^0.10.0
  json_annotation: ^4.5.0
dev_dependencies:
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0
  

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
